version: '3.8'

services:
  frontend:
    image: frontend-project:v3
    ports:
      - 5000:5000
  backend:
    image: backend-project:v2
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
    depends_on:
      - db
  redis:
    image: redis
  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - type: bind
        source: ./database
        target: /var/lib/postgresql/data
  reverse-proxy:
    image: nginx
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
