FROM node:16-alpine as build-stage
WORKDIR /usr/src/app
COPY . .
RUN npm install && \
    npm run build

FROM node:16-alpine
WORKDIR /usr/src/app
COPY --from=build-stage /usr/src/app/build ./build
RUN npm install -g serve && \
    adduser --disabled-password --gecos "" appuser
EXPOSE 5000
USER appuser
CMD ["serve", "-s", "-l", "5000", "build"]
